export class CharacterLook {
    public id: number;
    public characterId?: number = 0;
    public fatherFaceId?: number = 0;
    public motherFaceId?: number = 0;
    public skinColour?: number = 0;
    public shapeMix?: number = 0;
    public earsColor?: number = 0;
    public blemishesId?: number = 0;
    public blemishesOpacity?: number = 0;
    public ageingId?: number = 0;
    public ageingOpacity: number = 0;
    public blushId: number = 0;
    public blushOpacity: number = 0;
    public blushColor: number = 0;
    public beardId: number = 0;
    public beardOpacity: number = 0;
    public beardColor: number = 0;

    public noseWidth?: number = 0;
    public nosePeakHight?: number = 0;
    public nosePeakLenght?: number = 0;
    public noseBoneHigh?: number = 0;
    public nosePeakLowering?: number = 0;
    public noseBoneTwist?: number = 0;
    public eyeBrownHigh?: number = 0;
    public eyeBrownForward?: number = 0;
    public cheeksBoneHigh?: number = 0;
    public cheeksBoneWidth?: number = 0;
    public cheeksWidth?: number = 0;
    public eyesOpenning?: number = 0;
    public lipsThickness?: number = 0;
    public jawBoneWidth?: number = 0;
    public jawBoneBackLenght?: number = 0;
    public chimpBoneLowering?: number = 0;
    public chimpBoneLenght?: number = 0;
    public chimpBoneWidth?: number = 0;
    public chimpHole?: number = 0;
    public neckThikness?: number = 0;

    public eyebrowsId?: number = 0;
    public secondEyebrowsColor?: number = 0;
    public eyeBrowsOpacity: number = 0;
    public lipstickId: number = 0;
    public firstEyebrowsColor?: number = 0;
    public firstLipstickColor?: number = 0;
    public lipstickOpacity?: number = 0;
    public secondLipstickColor?: number = 0;
    public makeupId: number = 0;
    public firstMakeupColor?: number = 0;
    public makeupOpacity?: any = 0;
    public secondMakeupColor?: number = 0;
    public glassesId?: number = 0;
    public glassesTexture?: number = 0;
    public hairId?: number = 0;
    public hairTexture?: number = 0;
    public hairColor?: number = 0;
    public hairColorTwo?: number = 0;
    public hatId?: number = 0;
    public hatTexture?: number = 0;
    public topId?: number = 0;
    public topTexture?: number = 0;
    public torsoId?: number = 0;
    public torsoTexture?: number = 0;
    public undershirtId?: number = 0;
    public undershirtTexture?: number = 0;
    public legsId?: number = 0;
    public legsTexture?: number = 0;
    public shoesId?: number = 0;
    public shoesTexture?: number;
}

