export const weaponItemConfig = {
    weaponTakeOutAnims: [
        {
            WeaponName: 'MarksmanPistol',
            Hash: 3696079510,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,

        },
        {
            WeaponName: 'HeavyRevolver',
            Hash: 3249783761,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'HeavyRevolverMkII',
            Hash: 3415619887,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'DoubleActionRevolver',
            Hash: 25487034,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'Pistol',
            Hash: 453432689,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'PistolMkII',
            Hash: 3219281620,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'CombatPistol',
            Hash: 1593441988,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'APPistol',
            Hash: 584646201,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'StunGun',
            Hash: 911657153,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'Pistol50',
            Hash: 2578377531,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'SNSPistol',
            Hash: 3218215474,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'SNSPistolMkII',
            Hash: 2285322324,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'HeavyPistol',
            Hash: 3523564046,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
        {
            WeaponName: 'VintagePistol',
            Hash: 137902532,
            AnimDict: 'rcmjosh4',
            Anim: 'josh_leadout_cop2',
            Time: 800,
        },
    ],

    weaponHideAnims: [
        {
            WeaponName: 'MarksmanPistol',
            Hash: 3696079510,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,

        },
        {
            WeaponName: 'HeavyRevolver',
            Hash: 3249783761,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'HeavyRevolverMkII',
            Hash: 3415619887,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'DoubleActionRevolver',
            Hash: 25487034,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'Pistol',
            Hash: 453432689,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'PistolMkII',
            Hash: 3219281620,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'CombatPistol',
            Hash: 1593441988,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'APPistol',
            Hash: 584646201,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'StunGun',
            Hash: 911657153,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'Pistol50',
            Hash: 2578377531,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'SNSPistol',
            Hash: 3218215474,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'SNSPistolMkII',
            Hash: 2285322324,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'HeavyPistol',
            Hash: 3523564046,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
        {
            WeaponName: 'VintagePistol',
            Hash: 137902532,
            AnimDict: 'weapons@pistol@',
            Anim: 'aim_2_holster',
            Time: 180,
        },
    ],
};
